### ISSUE TITLE
Support for ACR122U on Raspberry Pi

### ISSUE THREAD

**Issue by nodecentral** [mcqn/node-red-contrib-nfc#4]
Hi,

I’ve got my ACR122U already set up and running on my pi (https://oneguyoneblog.com/2015/09/16/acr122u-nfc-usb-reader-raspberry-pi/) - before I install Node-Red, based on the above installation process, are you able to tell if the ACR122U is compatible with your add-on ?

Many thanks

**Comment by amcewen** [comment]
Hello!  I'm afraid this module talks direct to the SL030, rather than using libnfc, so it won't work with the ACR122U modules.
